title: Cà Phê Đắng
description: Viết cho thanh xuân của tôi
baseurl: "/"
url: "https://cafedang.xyz"
permalink: /:year/:month/:day/:title
repository: Kioku17/kioku17.github.io
paginate: 10

user: "Trần Khánh"
user_email: "trankhanh9227@gmail.com"
contact_url: "https://facebook.com/tnkxd"
google_tracking_id: "UA-96359860-1"
google_site_verification: "UA-96359860-1"
disqus_shortname: "kioku17"

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
sass:
  style: compressed
future: true