title: Cà Phê Đắng
description: Gửi tặng thanh xuân của tôi
domain: "cafedang.xyz"
baseurl: "/"
url: "https://cafedang.xyz"
permalink: /:title
repository: Kioku17/kioku17.github.io
paginate: 10

github_profile: "https://github.com/Kioku17"
user: "Trần Khánh"
nickname: "Tròm"
user_email: "trankhanh9227@gmail.com"
contact_url: "https://facebook.com/tnkxd"
google_tracking_id: "UA-96359860-1"
google_site_verification: "UA-96359860-1"

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
sass:
  style: compressed
future: true