title: Cà Phê Đắng
description: Gửi tặng thanh xuân của tôi
domain: "cafedang.xyz"
baseurl: "/"
url: "https://m.cafedang.xyz"
permalink: /:title
repository: Kioku17/kioku17.github.io
paginate: 10

github_profile: "https://github.com/Kioku17"
user: "Kioku17"
nickname: "Vá lốp có tâm"
user_email: "hocsinhvn2002@gmail.com"
contact_url: "https://facebook.com/tnkxd"
google_tracking_id: "UA-96359860-1"
google_site_verification: "UA-96359860-1"

# store in csv file
commentRead: "https://docs.google.com/forms/d/e/1FAIpQLSeAHm9mqzABiQ9h24ef3eWdQGEhJRIYMV2i3JucNZmqW41IOg"
commentPost: "https://docs.google.com/spreadsheets/d/1geQrNXq8fF0s6rLYBptD_xHI8xpjL8WDIcLHx2k8GL4"
commentPostUrl: "entry.404787257"
commentPostUsername: "entry.2003036143"
commentPostComment: "entry.432128806"

# category
girl: "Gái xinh"
meme: "Ảnh hài, ảnh chế"
story: "Góc truyện"

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
sass:
  style: compressed
future: true
